<?php

use Illuminate\Database\Migrations\Migration;
use Illuminate\Database\Schema\Blueprint;
use Illuminate\Support\Facades\Schema;

class CreateDefaultColumnsTable extends Migration
{
    /**
     * Run the migrations.
     *
     * @return void
     */
    public function up()
    {
        Schema::create('default_columns', function (Blueprint $table) {
            $table->uuid('id'); $table->primary('id');

            $table->string('table_name');
            $table->string('group')->nullable()->default(null);
            $table->string('column_name');
            $table->string('column_type_db');
            $table->string('column_type_orm');

            CommonMigrations::five($table);
        });

        DB::table('default_columns')
            ->insert([
                [ 'id' => Uuid::generate(), 'table_name' => 'instantaneous_data', 'column_name' => 'current_tariff_register', 'column_type_db' => 'int', 'column_type_orm' => 'integer' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'instantaneous_data', 'column_name' => 'signal_strength', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'instantaneous_data', 'column_name' => 'msn', 'column_type_db' => 'bigint', 'column_type_orm' => 'bigInteger' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'instantaneous_data', 'column_name' => 'frequency', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'instantaneous_data', 'column_name' => 'global_device_id', 'column_type_db' => 'varchar', 'column_type_orm' => 'string' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'instantaneous_data', 'column_name' => 'meter_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'instantaneous_data', 'column_name' => 'current_phase_a', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'instantaneous_data', 'column_name' => 'current_phase_b', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'instantaneous_data', 'column_name' => 'current_phase_c', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'instantaneous_data', 'column_name' => 'voltage_phase_a', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'instantaneous_data', 'column_name' => 'voltage_phase_b', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'instantaneous_data', 'column_name' => 'voltage_phase_c', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'instantaneous_data', 'column_name' => 'aggregate_active_pwr_pos', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'instantaneous_data', 'column_name' => 'aggregate_active_pwr_neg', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'instantaneous_data', 'column_name' => 'aggregate_active_pwr_abs', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'instantaneous_data', 'column_name' => 'aggregate_reactive_pwr_pos', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'instantaneous_data', 'column_name' => 'aggregate_reactive_pwr_neg', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'instantaneous_data', 'column_name' => 'aggregate_reactive_pwr_abs', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'instantaneous_data', 'column_name' => 'average_pf', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'instantaneous_data', 'column_name' => 'mdc_read_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'instantaneous_data', 'column_name' => 'db_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'msn', 'column_type_db' => 'bigint', 'column_type_orm' => 'bigInteger' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'global_device_id', 'column_type_db' => 'varchar', 'column_type_orm' => 'string' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'meter_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'active_energy_pos_t1', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'active_energy_pos_t2', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'active_energy_pos_t3', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'active_energy_pos_t4', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'active_energy_pos_tl', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'active_energy_neg_t1', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'active_energy_neg_t2', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'active_energy_neg_t3', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'active_energy_neg_t4', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'active_energy_neg_tl', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'active_energy_abs_t1', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'active_energy_abs_t2', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'active_energy_abs_t3', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'active_energy_abs_t4', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'active_energy_abs_tl', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'reactive_energy_pos_t1', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'reactive_energy_pos_t2', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'reactive_energy_pos_t3', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'reactive_energy_pos_t4', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'reactive_energy_pos_tl', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'reactive_energy_neg_t1', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'reactive_energy_neg_t2', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'reactive_energy_neg_t3', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'reactive_energy_neg_t4', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'reactive_energy_neg_tl', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'reactive_energy_abs_t1', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'reactive_energy_abs_t2', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'reactive_energy_abs_t3', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'reactive_energy_abs_t4', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'reactive_energy_abs_tl', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'active_mdi_pos_t1', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'active_mdi_pos_t2', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'active_mdi_pos_t3', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'active_mdi_pos_t4', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'active_mdi_pos_tl', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'active_mdi_neg_t1', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'active_mdi_neg_t2', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'active_mdi_neg_t3', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'active_mdi_neg_t4', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'active_mdi_neg_tl', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'active_mdi_abs_t1', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'active_mdi_abs_t2', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'active_mdi_abs_t3', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'active_mdi_abs_t4', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'active_mdi_abs_tl', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'cumulative_mdi_pos_t1', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'cumulative_mdi_pos_t2', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'cumulative_mdi_pos_t3', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'cumulative_mdi_pos_t4', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'cumulative_mdi_pos_tl', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'cumulative_mdi_neg_t1', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'cumulative_mdi_neg_t2', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'cumulative_mdi_neg_t3', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'cumulative_mdi_neg_t4', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'cumulative_mdi_neg_tl', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'cumulative_mdi_abs_t1', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'cumulative_mdi_abs_t2', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'cumulative_mdi_abs_t3', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'cumulative_mdi_abs_t4', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'cumulative_mdi_abs_tl', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'mdc_read_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'billing_data', 'column_name' => 'db_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'msn', 'column_type_db' => 'bigint', 'column_type_orm' => 'bigInteger' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'global_device_id', 'column_type_db' => 'varchar', 'column_type_orm' => 'string' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'meter_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'active_energy_pos_t1', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'active_energy_pos_t2', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'active_energy_pos_t3', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'active_energy_pos_t4', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'active_energy_pos_tl', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'active_energy_neg_t1', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'active_energy_neg_t2', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'active_energy_neg_t3', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'active_energy_neg_t4', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'active_energy_neg_tl', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'active_energy_abs_t1', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'active_energy_abs_t2', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'active_energy_abs_t3', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'active_energy_abs_t4', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'active_energy_abs_tl', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'reactive_energy_pos_t1', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'reactive_energy_pos_t2', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'reactive_energy_pos_t3', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'reactive_energy_pos_t4', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'reactive_energy_pos_tl', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'reactive_energy_neg_t1', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'reactive_energy_neg_t2', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'reactive_energy_neg_t3', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'reactive_energy_neg_t4', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'reactive_energy_neg_tl', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'reactive_energy_abs_t1', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'reactive_energy_abs_t2', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'reactive_energy_abs_t3', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'reactive_energy_abs_t4', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'reactive_energy_abs_tl', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'active_mdi_pos_t1', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'active_mdi_pos_t2', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'active_mdi_pos_t3', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'active_mdi_pos_t4', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'active_mdi_pos_tl', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'active_mdi_neg_t1', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'active_mdi_neg_t2', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'active_mdi_neg_t3', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'active_mdi_neg_t4', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'active_mdi_neg_tl', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'active_mdi_abs_t1', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'active_mdi_abs_t2', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'active_mdi_abs_t3', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'active_mdi_abs_t4', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'active_mdi_abs_tl', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'cumulative_mdi_pos_t1', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'cumulative_mdi_pos_t2', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'cumulative_mdi_pos_t3', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'cumulative_mdi_pos_t4', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'cumulative_mdi_pos_tl', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'cumulative_mdi_neg_t1', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'cumulative_mdi_neg_t2', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'cumulative_mdi_neg_t3', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'cumulative_mdi_neg_t4', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'cumulative_mdi_neg_tl', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'cumulative_mdi_abs_t1', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'cumulative_mdi_abs_t2', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'cumulative_mdi_abs_t3', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'cumulative_mdi_abs_t4', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'cumulative_mdi_abs_tl', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'longitude', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'latitude', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'picture_1', 'column_type_db' => 'blob', 'column_type_orm' => 'binary' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'picture_2', 'column_type_db' => 'blob', 'column_type_orm' => 'binary' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'reading_mode', 'column_type_db' => 'int', 'column_type_orm' => 'integer' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'mdi_reset_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'reset_count', 'column_type_db' => 'int', 'column_type_orm' => 'integer' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'mdc_read_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'monthly_billing_data', 'column_name' => 'db_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'msn', 'column_type_db' => 'bigint', 'column_type_orm' => 'bigInteger' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'global_device_id', 'column_type_db' => 'varchar', 'column_type_orm' => 'string' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'meter_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'frequency', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'channel_id', 'column_type_db' => 'int', 'column_type_orm' => 'integer' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'interval', 'column_type_db' => 'int', 'column_type_orm' => 'integer' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'active_energy_pos_t1', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'active_energy_pos_t2', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'active_energy_pos_t3', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'active_energy_pos_t4', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'active_energy_pos_tl', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'active_energy_neg_t1', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'active_energy_neg_t2', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'active_energy_neg_t3', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'active_energy_neg_t4', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'active_energy_neg_tl', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'active_energy_abs_t1', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'active_energy_abs_t2', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'active_energy_abs_t3', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'active_energy_abs_t4', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'active_energy_abs_tl', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'reactive_energy_pos_t1', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'reactive_energy_pos_t2', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'reactive_energy_pos_t3', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'reactive_energy_pos_t4', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'reactive_energy_pos_tl', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'reactive_energy_neg_t1', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'reactive_energy_neg_t2', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'reactive_energy_neg_t3', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'reactive_energy_neg_t4', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'reactive_energy_neg_tl', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'reactive_energy_abs_t1', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'reactive_energy_abs_t2', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'reactive_energy_abs_t3', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'reactive_energy_abs_t4', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'reactive_energy_abs_tl', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'active_mdi_pos_t1', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'active_mdi_pos_t2', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'active_mdi_pos_t3', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'active_mdi_pos_t4', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'active_mdi_pos_tl', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'active_mdi_neg_t1', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'active_mdi_neg_t2', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'active_mdi_neg_t3', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'active_mdi_neg_t4', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'active_mdi_neg_tl', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'active_mdi_abs_t1', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'active_mdi_abs_t2', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'active_mdi_abs_t3', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'active_mdi_abs_t4', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'active_mdi_abs_tl', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'cumulative_mdi_pos_t1', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'cumulative_mdi_pos_t2', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'cumulative_mdi_pos_t3', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'cumulative_mdi_pos_t4', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'cumulative_mdi_pos_tl', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'cumulative_mdi_neg_t1', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'cumulative_mdi_neg_t2', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'cumulative_mdi_neg_t3', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'cumulative_mdi_neg_t4', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'cumulative_mdi_neg_tl', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'cumulative_mdi_abs_t1', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'cumulative_mdi_abs_t2', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'cumulative_mdi_abs_t3', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'cumulative_mdi_abs_t4', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'cumulative_mdi_abs_tl', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'current_phase_a', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'current_phase_b', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'current_phase_c', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'voltage_phase_a', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'voltage_phase_b', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'voltage_phase_c', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'active_pwr_pos_phase_a', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'active_pwr_pos_phase_b', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'active_pwr_pos_phase_c', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'aggregate_active_pwr_pos', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'active_pwr_neg_phase_a', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'active_pwr_neg_phase_b', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'active_pwr_neg_phase_c', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'aggregate_active_pwr_neg', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'aggregate_active_pwr_abs', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'reactive_pwr_pos_phase_a', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'reactive_pwr_pos_phase_b', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'reactive_pwr_pos_phase_c', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'aggregate_reactive_pwr_pos', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'reactive_pwr_neg_phase_a', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'reactive_pwr_neg_phase_b', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'reactive_pwr_neg_phase_c', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'aggregate_reactive_pwr_neg', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'aggregate_reactive_pwr_abs', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'average_pf', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'mdc_read_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'load_profile_data', 'column_name' => 'db_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'events', 'column_name' => 'msn', 'column_type_db' => 'bigint', 'column_type_orm' => 'bigInteger' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'events', 'column_name' => 'global_device_id', 'column_type_db' => 'varchar', 'column_type_orm' => 'string' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'events', 'column_name' => 'event_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'events', 'column_name' => 'event_code', 'column_type_db' => 'int', 'column_type_orm' => 'integer' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'events', 'column_name' => 'event_counter', 'column_type_db' => 'bigint', 'column_type_orm' => 'bigInteger' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'events', 'column_name' => 'event_description', 'column_type_db' => 'varchar', 'column_type_orm' => 'string' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'events', 'column_name' => 'mdc_read_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'events', 'column_name' => 'db_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'msn', 'column_type_db' => 'bigint', 'column_type_orm' => 'bigInteger' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'global_device_id', 'column_type_db' => 'varchar', 'column_type_orm' => 'string' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'last_command', 'column_type_db' => 'varchar', 'column_type_orm' => 'string' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'last_command_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'last_command_resp', 'column_type_db' => 'varchar', 'column_type_orm' => 'string' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'last_command_resp_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'active_energy_pos_tl', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'active_energy_pos_tl_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'active_energy_neg_tl', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'active_energy_neg_tl_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'reactive_energy_pos_tl', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'reactive_energy_pos_tl_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'reactive_energy_neg_tl', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'reactive_energy_neg_tl_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'aggregate_active_energy_abs_tl', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'aggregate_active_energy_abs_tl_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'aggregate_active_pwr_pos', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'aggregate_active_pwr_pos_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'aggregate_active_pwr_neg', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'aggregate_active_pwr_neg_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'aggregate_reactive_pwr_pos', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'aggregate_reactive_pwr_pos_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'aggregate_reactive_pwr_neg', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'aggregate_reactive_pwr_neg_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'aggregate_reactive_energy_abs_tl', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'aggregate_reactive_energy_abs_tl_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'current_phase_a', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'current_phase_b', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'current_phase_c', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'voltage_phase_a', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'voltage_phase_b', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'voltage_phase_c', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'frequency', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'average_pf', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'last_contactor_on_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'last_contactor_off_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'last_communication_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'last_signal_strength', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'power_status', 'column_type_db' => 'int', 'column_type_orm' => 'integer' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'power_status_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'auxr_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'auxr_status', 'column_type_db' => 'varchar', 'column_type_orm' => 'string' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'dvtm_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'dvtm_meter_clock', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'sanc_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'sanc_load_limit', 'column_type_db' => 'varchar', 'column_type_orm' => 'string' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'sanc_maximum_retries', 'column_type_db' => 'varchar', 'column_type_orm' => 'string' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'sanc_retry_interval', 'column_type_db' => 'varchar', 'column_type_orm' => 'string' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'sanc_threshold_duration', 'column_type_db' => 'varchar', 'column_type_orm' => 'string' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'sanc_retry_clear_interval', 'column_type_db' => 'varchar', 'column_type_orm' => 'string' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'lsch_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'lsch_start_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'lsch_end_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'lsch_load_shedding_slabs', 'column_type_db' => 'text', 'column_type_orm' => 'text' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'tiou_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'tiou_day_profile', 'column_type_db' => 'text', 'column_type_orm' => 'text' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'tiou_week_profile', 'column_type_db' => 'text', 'column_type_orm' => 'text' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'tiou_season_profile', 'column_type_db' => 'text', 'column_type_orm' => 'text' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'tiou_holiday_profile', 'column_type_db' => 'text', 'column_type_orm' => 'text' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'tiou_activation_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'ippo_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'ippo_primary_ip_address', 'column_type_db' => 'varchar', 'column_type_orm' => 'string' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'ippo_secondary_ip_address', 'column_type_db' => 'varchar', 'column_type_orm' => 'string' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'ippo_primary_port', 'column_type_db' => 'varchar', 'column_type_orm' => 'string' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'ippo_secondary_port', 'column_type_db' => 'varchar', 'column_type_orm' => 'string' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'mdsm_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'mdsm_activation_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'mdsm_data_type', 'column_type_db' => 'varchar', 'column_type_orm' => 'string' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'mdsm_sampling_interval', 'column_type_db' => 'varchar', 'column_type_orm' => 'string' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'mdsm_sampling_initial_time', 'column_type_db' => 'varchar', 'column_type_orm' => 'string' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'oppo_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'oppo_optical_port_on_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'oppo_optical_port_off_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'wsim_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'wsim_wakeup_number_1', 'column_type_db' => 'varchar', 'column_type_orm' => 'string' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'wsim_wakeup_number_2', 'column_type_db' => 'varchar', 'column_type_orm' => 'string' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'wsim_wakeup_number_3', 'column_type_db' => 'varchar', 'column_type_orm' => 'string' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'mtst_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'mtst_meter_activation_status', 'column_type_db' => 'varchar', 'column_type_orm' => 'string' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'dmdt_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'dmdt_communication_mode', 'column_type_db' => 'varchar', 'column_type_orm' => 'string' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'dmdt_bidirectional_device', 'column_type_db' => 'varchar', 'column_type_orm' => 'string' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'dmdt_communication_type', 'column_type_db' => 'varchar', 'column_type_orm' => 'string' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'dmdt_communication_interval', 'column_type_db' => 'varchar', 'column_type_orm' => 'string' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'dmdt_phase', 'column_type_db' => 'varchar', 'column_type_orm' => 'string' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'dmdt_meter_type', 'column_type_db' => 'varchar', 'column_type_orm' => 'string' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'mdi_reset_date', 'column_type_db' => 'int', 'column_type_orm' => 'integer' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'meter_visuals', 'column_name' => 'mdi_reset_time', 'column_type_db' => 'varchar', 'column_type_orm' => 'string' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'device_communication_history', 'column_name' => 'msn', 'column_type_db' => 'bigint', 'column_type_orm' => 'bigInteger' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'device_communication_history', 'column_name' => 'global_device_id', 'column_type_db' => 'varchar', 'column_type_orm' => 'string' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'device_communication_history', 'column_name' => 'meter_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'device_communication_history', 'column_name' => 'communication_status', 'column_type_db' => 'int', 'column_type_orm' => 'integer' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'device_communication_history', 'column_name' => 'message_log', 'column_type_db' => 'text', 'column_type_orm' => 'text' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'device_communication_history', 'column_name' => 'longitude', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'device_communication_history', 'column_name' => 'latitude', 'column_type_db' => 'decimal', 'column_type_orm' => 'decimal' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'device_communication_history', 'column_name' => 'mdc_read_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
                [ 'id' => Uuid::generate(), 'table_name' => 'device_communication_history', 'column_name' => 'db_datetime', 'column_type_db' => 'datetime', 'column_type_orm' => 'datetime' ],
            ]);
    }

    /**
     * Reverse the migrations.
     *
     * @return void
     */
    public function down()
    {
        Schema::dropIfExists('default_columns');
    }
}
